# Generated by Django 2.1.3 on 2020-01-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagefile',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
