# Generated by Django 2.1.3 on 2020-01-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoupload', '0002_auto_20200122_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagefile',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
