# Generated by Django 2.1.3 on 2020-01-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoupload', '0004_auto_20200124_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='yearField',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images2/yearField'),
        ),
    ]
