# Generated by Django 2.1.3 on 2020-02-03 20:50

from django.db import migrations, models
import photoupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('photoupload', '0005_auto_20200125_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['yearField']},
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='memories',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=photoupload.models.path_name),
        ),
    ]
