# Generated by Django 2.1.3 on 2020-02-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoupload', '0007_image_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
